Repository GSM-MSG/Took-iOS, pull requests merged in 2022-09, with the labels that each got.

#7 🔀 :: CI를 위한 테스트 제작
  Projects/Modules/ThirdPartyLib/Tests/.gitkeep
  Projects/Modules/ThirdPartyLib/Tests/TargetTest.swift
  Projects/Modules/Utility/Tests/.gitkeep
  Projects/Modules/Utility/Tests/TargetTest.swift
Labels: ⚙ Setting, 1️⃣Priority: High

#5 🔀:: feature 생성 자동화 코드
  Scripts/generate_new_feature.py
Labels: 0️⃣Priority: Critical, ✨ Feature

#10 🔀 :: NFC Reader
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Projects/App/Project.swift
  Projects/App/Support/Info.plist
  Projects/App/Support/Took-iOS.entitlements
  Projects/Features/CardFeature/Project.swift
  Projects/Features/CardListFeature/Project.swift
  Projects/Modules/NFCModule/Derived/InfoPlists/NFCModule-Info.plist
  Projects/Modules/NFCModule/Derived/InfoPlists/NFCModuleTests-Info.plist
  Projects/Modules/NFCModule/Project.swift
  Projects/Modules/NFCModule/Sources/NFCReader.swift
  Projects/Modules/NFCModule/Tests/.gitkeep
  Projects/Modules/NFCModule/Tests/TargetTest.swift
Labels: 1️⃣Priority: High, ✨ Feature

#12 🔀 :: 디자인 시스템 - Color 구현
  Projects/UsertInterfaces/DesignSystem/Derived/Sources/TuistAssets+DesignSystem.swift
  Projects/UsertInterfaces/DesignSystem/Derived/Sources/TuistBundle+DesignSystem.swift
  Projects/UsertInterfaces/DesignSystem/Project.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/Black.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/DarkGray.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/Gray.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/LightGray.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/Strok.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/TransparencyBoxBg.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/VeryDarkGray.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/VeryVeryDarkGray.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/White.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Sources/Color/ColorSystem.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Feature.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Gradient/PrimaryGradient.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical

#14 🔀:: (#13)TookCheckbox
  Projects/UsertInterfaces/DesignSystem/Sources/Checkbox/TookCheckbox.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Checkbox/TookCheckboxStyle.swift
Labels: 0️⃣Priority: Critical, ✨ Feature

#17 🔀 :: Subcheckbox
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+MaskContent.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+if.swift
  Projects/UsertInterfaces/DesignSystem/Sources/SubCheckbox/TookSubCheckbox.swift
  Projects/UsertInterfaces/DesignSystem/Sources/SubCheckbox/TookSubCheckboxStyle.swift
Labels: 1️⃣Priority: High, ✨ Feature

#18 🔀 :: Font DesignSystem
  Projects/UsertInterfaces/DesignSystem/Sources/Typo/Typography.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical, ✨ Feature

#20 🔀 :: 디자인 시스템 - 버튼 구현
  Projects/UsertInterfaces/DesignSystem/Sources/Button/DefaultButton/TookButton.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Button/DefaultButton/TookButtonStyle.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Typo/Typography.swift
Labels: ⚙ Setting, 1️⃣Priority: High, ✨ Feature

#24 🔀 :: 디자인 시스템 - 이미지 - Background
  Projects/UsertInterfaces/DesignSystem/Derived/Sources/TuistAssets+DesignSystem.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Images.xcassets/Background.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Images.xcassets/Background.imageset/Start-1.png
  Projects/UsertInterfaces/DesignSystem/Resources/Images.xcassets/Background.imageset/Start-2.png
  Projects/UsertInterfaces/DesignSystem/Resources/Images.xcassets/Background.imageset/Start.png
  Projects/UsertInterfaces/DesignSystem/Resources/Images.xcassets/Contents.json
  Projects/UsertInterfaces/DesignSystem/Sources/Color/ColorSystem.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Image/TookImage.swift
Labels: ⚙ Setting, 1️⃣Priority: High, ✨ Feature

#31 🔀 :: Error Color 추가
  Projects/UsertInterfaces/DesignSystem/Derived/Sources/TuistAssets+DesignSystem.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/Error.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Sources/Color/ColorSystem.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical, ⚡️ Simple

#25 🔀 :: Intro Feature UI 개발
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/Application/TookApp.swift
  Projects/Features/CommonFeature/Sources/Feature.swift
  Projects/Features/CommonFeature/Sources/SceneState.swift
  Projects/Features/CommonFeature/Sources/SceneStateModel.swift
  Projects/Features/IntroFeature/Sources/IntroComponent.swift
  Projects/Features/IntroFeature/Sources/IntroFeature.swift
  Projects/Features/IntroFeature/Sources/IntroView.swift
  Projects/Features/MainFeature/Sources/MainComponent.swift
  Projects/Features/MainFeature/Sources/MainFeature.swift
  Projects/Features/MainFeature/Sources/MainView.swift
  Projects/Features/RootFeature/Sources/RootComponent.swift
  Projects/Features/RootFeature/Sources/RootView.swift
  Projects/Features/RootFeature/Sources/RootViewModel.swift
  Projects/Features/VerifyFeature/Sources/VerifyFeature.swift
  Projects/UsertInterfaces/DesignSystem/Project.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Typo/Typography.swift
Labels: 1️⃣Priority: High, ✨ Feature

#27 🔀 :: SwiftLint Lint 문제 해결
  Projects/Features/CardFeature/Sources/CardFeature.swift
  Projects/Features/CardListFeature/Sources/CardListFeature.swift
  Projects/Features/RootFeature/Project.swift
  Projects/Features/SettingFeature/Project.swift
  Projects/Features/SettingFeature/Sources/SettingFeature.swift
  Projects/Features/SigninFeature/Project.swift
  Projects/Features/SigninFeature/Sources/SigninFeature.swift
  Projects/Features/SignupFeature/Sources/SignupFeature.swift
  Projects/Features/VerifyFeature/Project.swift
  Projects/Features/VerifyFeature/Sources/VerifyFeature.swift
  Projects/Modules/Utility/Sources/Utility.swift
  Projects/Services/DataModule/Sources/Repositories/RemoveMe2.swift
  Projects/Services/DataModule/Sources/Utils/RemoveMe0.swift
  Projects/Services/DomainModule/Sources/Entities/RemoveMe7.swift
  Projects/Services/DomainModule/Sources/Repositories/RemoveMe9.swift
  Projects/Services/DomainModule/Sources/UseCases/RemoveMe10.swift
  Projects/UsertInterfaces/LocalizableManager/Project.swift
Labels: 3️⃣Priority: Low, ⚡️ Simple, 🔨 Refactor

#33 🔀 :: 디자인 시스템 - Icon 구현
  .gitignore
  Projects/UsertInterfaces/DesignSystem/Derived/Sources/TuistAssets+DesignSystem.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Card.imageset/Card-1.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Card.imageset/Card-2.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Card.imageset/Card.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Card.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Gear.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Gear.imageset/Gear-1.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Gear.imageset/Gear-2.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Gear.imageset/Gear.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Horizontal.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Horizontal.imageset/Horizontal-1.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Horizontal.imageset/Horizontal-2.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Horizontal.imageset/Horizontal.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/TabCardList.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/TabCardList.imageset/TabCardList-1.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/TabCardList.imageset/TabCardList-2.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/TabCardList.imageset/TabCardList.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/TabHome.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/TabHome.imageset/TabHome-1.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/TabHome.imageset/TabHome-2.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/TabHome.imageset/TabHome.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Vertical.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Vertical.imageset/Vertical-1.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Vertical.imageset/Vertical-2.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Icons.xcassets/Vertical.imageset/Vertical.svg
  Projects/UsertInterfaces/DesignSystem/Sources/Icon/TookIcon.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical, ✨ Feature

#44 🔀 :: TookTextField 디자인 시스템
  Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical

#41 🔀 :: 명함 엔티티 작업
  Projects/Services/DomainModule/Sources/Entities/BusinessCard.swift
  Projects/Services/DomainModule/Sources/Entities/RemoveMe7.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical

#52 🔀 :: AuthAPI
  Projects/Modules/ErrorModule/Sources/TookError.swift
  Projects/Services/APIKit/Sources/AuthAPI.swift
  Projects/Services/DataMappingModule/Sources/Feature.swift
  Projects/Services/DataMappingModule/Sources/Request/SigninRequestDTO.swift
  Projects/Services/DataMappingModule/Sources/Request/SignupRequestDTO.swift
Labels: 📬 API, 0️⃣Priority: Critical

#50 🔀 :: BaseRemoteDataSource
  Projects/Modules/Utility/Sources/DateUtil.swift
  Projects/Modules/Utility/Sources/Utility.swift
  Projects/Services/DataMappingModule/Sources/NoResponse.swift
  Projects/Services/NetworkModule/Sources/BaseRemoteDataSource.swift
  Projects/Services/NetworkModule/Sources/Feature.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical, ✨ Feature

#54 🔀 :: 회원가입 Feature
  Projects/App/Sources/Application/AppComponent+RemoteDataSource.swift
  Projects/App/Sources/Application/AppComponent+Repository.swift
  Projects/App/Sources/Application/AppComponent+UseCase.swift
  Projects/App/Sources/Application/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/Application/TookApp.swift
  Projects/App/Support/Info.plist
  Projects/Features/IntroFeature/Sources/IntroComponent.swift
  Projects/Features/IntroFeature/Sources/IntroView.swift
  Projects/Features/SignupFeature/Sources/SignupComponent.swift
  Projects/Features/SignupFeature/Sources/SignupFeature.swift
  Projects/Features/SignupFeature/Sources/SignupView.swift
  Projects/Features/SignupFeature/Sources/SignupViewModel.swift
  Projects/Features/SignupFeature/Sources/Terms/Terms.swift
  Projects/Features/SignupFeature/Sources/Terms/TermsView.swift
  Projects/Modules/KeychainModule/Sources/DefaultKeychain.swift
  Projects/Services/DataModule/Sources/Repositories/AuthRepositoryImpl.swift
  Projects/Services/DataModule/Sources/Repositories/RemoveMe2.swift
  Projects/Services/DataModule/Sources/UseCases/Auth/LogoutUseCaseImpl.swift
  Projects/Services/DataModule/Sources/UseCases/Auth/SigninUseCaseImpl.swift
  Projects/Services/DataModule/Sources/UseCases/Auth/SignupUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/Repositories/AuthRepository.swift
  Projects/Services/DomainModule/Sources/Repositories/RemoveMe9.swift
  Projects/Services/DomainModule/Sources/UseCases/Auth/LogoutUseCase.swift
  Projects/Services/DomainModule/Sources/UseCases/Auth/SigninUseCase.swift
  Projects/Services/DomainModule/Sources/UseCases/Auth/SignupUseCase.swift
  Projects/Services/DomainModule/Sources/UseCases/RemoveMe10.swift
  Projects/Services/NetworkModule/Sources/AuthRemoteDataSource.swift
  Projects/Services/NetworkModule/Sources/BaseRemoteDataSource.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Checkbox/TookCheckbox.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+adaptiveSheet.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+configBackButton.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+cornerRadius.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+navigate.swift
  Projects/UsertInterfaces/DesignSystem/Sources/SubCheckbox/TookSubCheckbox.swift
  Projects/UsertInterfaces/DesignSystem/Sources/TextField/SecureTookTextField.swift
  Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
Labels: 📬 API, 0️⃣Priority: Critical, ✨ Feature

#56 🔀 :: Login UI
  Projects/App/Sources/Application/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/Application/TookApp.swift
  Projects/Features/SigninFeature/Sources/SigninComponent.swift
  Projects/Features/SigninFeature/Sources/SigninFeature.swift
  Projects/Features/SigninFeature/Sources/SigninView.swift
  Projects/Features/SigninFeature/Sources/SigninViewModel.swift
Labels: 0️⃣Priority: Critical, ✨ Feature

#58 🔀 :: 디자인 시스템 Bold -> Semibold
  Projects/Features/SignupFeature/Sources/Terms/TermsView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/TextField/SecureTookTextField.swift
  Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Typo/Typography.swift
Labels: 1️⃣Priority: High, ⚡️ Simple, 🔨 Refactor

#60 🔀 :: Verify Feature
  Projects/App/Sources/Application/AppComponent+RemoteDataSource.swift
  Projects/App/Sources/Application/AppComponent+Repository.swift
  Projects/App/Sources/Application/AppComponent+UseCase.swift
  Projects/App/Sources/Application/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/Application/TookApp.swift
  Projects/App/Support/Info.plist
  Projects/Features/CommonFeature/Sources/BaseViewModel.swift
  Projects/Features/SigninFeature/Sources/SigninView.swift
  Projects/Features/SignupFeature/Sources/SignupComponent.swift
  Projects/Features/SignupFeature/Sources/SignupView.swift
  Projects/Features/SignupFeature/Sources/SignupViewModel.swift
  Projects/Features/VerifyFeature/Sources/VerifyComponent.swift
  Projects/Features/VerifyFeature/Sources/VerifyFeature.swift
  Projects/Features/VerifyFeature/Sources/VerifyView.swift
  Projects/Features/VerifyFeature/Sources/VerifyViewModel.swift
  Projects/Modules/ErrorModule/Sources/TookError.swift
  Projects/Services/APIKit/Sources/EmailAPI.swift
  Projects/Services/APIKit/Sources/TookAPI.swift
  Projects/Services/DataModule/Sources/Repositories/EmailRepositoryImpl.swift
  Projects/Services/DataModule/Sources/UseCases/Email/EmailVerifyUseCaseImpl.swift
  Projects/Services/DataModule/Sources/UseCases/Email/SendEmailUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/Repositories/EmailRepository.swift
  Projects/Services/DomainModule/Sources/UseCases/Email/EmailVerifyUseCase.swift
  Projects/Services/DomainModule/Sources/UseCases/Email/SendEmailUseCase.swift
  Projects/Services/NetworkModule/Sources/EmailRemoteDataSource.swift
Labels: 0️⃣Priority: Critical

#63 🔀 :: 디자인 시스템 - 스낵바
  Projects/UsertInterfaces/DesignSystem/Derived/Sources/TuistAssets+DesignSystem.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Colors.xcassets/SystemGreen.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Sources/Color/ColorSystem.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Snackbar/Snackbar.swift
Labels: 0️⃣Priority: Critical, ✨ Feature

#35 🔀 :: 메인 탭바 UI
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Projects/App/Sources/Application/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/CommonFeature/Sources/SceneState.swift
  Projects/Features/CommonFeature/Sources/SceneStateModel.swift
  Projects/Features/CommonFeature/Sources/StorageKeys.swift
  Projects/Features/MainFeature/Project.swift
  Projects/Features/MainFeature/Sources/MainTabItemView.swift
  Projects/Features/MainFeature/Sources/MainView.swift
  Projects/Features/NewCardFeature/Derived/InfoPlists/NewCardFeature-Info.plist
  Projects/Features/NewCardFeature/Derived/InfoPlists/NewCardFeatureTests-Info.plist
  Projects/Features/NewCardFeature/Project.swift
  Projects/Features/NewCardFeature/Sources/NewCardFeature.swift
  Projects/Features/NewCardFeature/Tests/TargetTests.swift
  Projects/Features/RootFeature/Sources/RootComponent.swift
  Projects/Features/RootFeature/Sources/RootView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+cornerRadius.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Icon/TookIcon.swift
  graph.png
Labels: 0️⃣Priority: Critical, ✨ Feature

#65 🔀 :: User API제작
  Projects/App/Sources/Application/AppComponent+RemoteDataSource.swift
  Projects/App/Sources/Application/AppComponent+Repository.swift
  Projects/App/Sources/Application/AppComponent+UseCase.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Modules/ErrorModule/Sources/TookError.swift
  Projects/Services/APIKit/Sources/UserAPI.swift
  Projects/Services/DataMappingModule/Sources/Response/BusinessCardResponseDTO.swift
  Projects/Services/DataModule/Sources/Repositories/UserRepositoryImpl.swift
  Projects/Services/DataModule/Sources/UseCases/User/MyBusinessCardUseCaseImpl.swift
  Projects/Services/DataModule/Sources/UseCases/User/RenewalPasswordUseCaseImpl.swift
  Projects/Services/DataModule/Sources/UseCases/User/WithdrawUseCaseImpl.swift
  Projects/Services/DomainModule/Sources/DataUtil/ToDate.swift
  Projects/Services/DomainModule/Sources/Entities/BusinessCard.swift
  Projects/Services/DomainModule/Sources/Repositories/UserRepository.swift
  Projects/Services/DomainModule/Sources/UseCases/User/MyBusinessCardUseCase.swift
  Projects/Services/DomainModule/Sources/UseCases/User/RenewalPasswordUseCase.swift
  Projects/Services/DomainModule/Sources/UseCases/User/WithdrawUseCase.swift
  Projects/Services/NetworkModule/Sources/UserRemoteDataSource.swift
Labels: 1️⃣Priority: High, 📬 API

#66 🔀 :: 명함 교환 페이지
  Projects/App/Sources/Application/AppComponent.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Sources/Application/TookApp.swift
  Projects/Features/NewCardFeature/Sources/NewCardComponent.swift
  Projects/Features/NewCardFeature/Sources/NewCardFeature.swift
  Projects/Features/NewCardFeature/Sources/NewCardView.swift
  Projects/Features/NewCardFeature/Sources/NewCardViewModel.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extensions/View+ImagePicker.swift
Labels: ⚙ Setting, 0️⃣Priority: Critical, 🙋‍♂️ Question, ✨ Feature, 🔨 Refactor
